version: '3.9'
services:
  apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    # volumes:
    #   - .:/workspace:cached
